-- 코드를 입력하세요
SELECT B.AUTHOR_ID, 
        A.AUTHOR_NAME, 
        B.CATEGORY, 
        SUM(B.PRICE*B_S.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES B_S ON B.BOOK_ID = B_S.BOOK_ID
WHERE SUBSTR(B_S.SALES_DATE, 1, 7) = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC